---
groups:
  - name: master
    jobs:
      - hadolint
      - rubocop
      - rspec
      - shellcheck
      - build
      - testinfra

resources:
  - name: resource_git
    type: git
    icon: github
    source:
      uri: https://github.com/Firebladee/docker_libvirt.git
      branch: concourse

  - name: docker_temp
    type: docker-image
    icon: docker
    source:
      email: ((docker_hub_email))
      username: ((docker_hub_username))
      password: ((docker_hub_password))
      repository: ((docker_hub_username))/testing

jobs:
  - name: hadolint
    public: true
    plan:
      - get: resource_git
        trigger: true
      - task: validate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hadolint/hadolint
          inputs:
            - name: resource_git
          run:
            path: hadolint
            args:
              - resource_git/systemd/Dockerfile

  - name: rubocop
    public: true
    plan:
      - get: resource_git
        trigger: true
      - task: rubocop
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ruby
          inputs:
            - name: resource_git
          run:
            path: sh
            args:
              - -exc
              - |
                gem install rubocop
                cd resource_git
                rubocop

  - name: rspec
    public: true
    plan:
      - get: resource_git
        trigger: true
        passed:
          - rubocop
      - task: rspec
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ruby
          inputs:
            - name: resource_git
          run:
            path: sh
            args:
              - -exc
              - |
                bundle
                rspec
        
  - name: shellcheck
    public: true
    plan:
      - get: resource_git
        trigger: true
      - task: shellcheck
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: koalaman/shellcheck-alpine
          inputs:
            - name: resource_git
          run:
            path: sh
            args:
              - -exc
              - |
                shellcheck resource_git/systemd/*.sh

  - name: build
    public: true
    plan:
      - get: resource_git
        passed:
          - hadolint
        trigger: true
      - put: docker_temp
        params:
          build: resource_git/systemd

  - name: testinfra
    public: true
    plan:
      - get: resource_git
        passed:
          - shellcheck
          - build
          - rspec
        trigger: true
      - task: hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: centos
          run:
            path: echo
            args: ["Testinfra"]
