version: 2.1

workflows:
  lint:
    jobs:
      - rubocop
      - hadolint
      - shellcheck

orbs:
  rubocop: hanachin/rubocop@0.0.6
  docker: circleci/docker@1.4.0
  shellcheck: circleci/shellcheck@2.0.0
jobs:
  rubocop:
    jobs:
      - rubocop/rubocop:
          options:
            --parallel

  hadolint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile

  #rspec:
  #  jobs:
  #    - rspec

  shellcheck:
    jobs:
      - shellcheck/check
          dir: .

  build_test:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/testing
          use-docker-credentials-store: true

  #rspec2:
  #  jobs:
  #    - testinfra

  docker_build:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/libvirt
          use-docker-credentials-store: true

