version: 2.1

#workflows:
#  lint:
#    jobs:
#      - rubocop
#      - hadolint
#      - shellcheck

orbs:
  rubocop: hanachin/rubocop@0.0.6
  docker: circleci/docker@1.4.0
  shellcheck: circleci/shellcheck@2.0.0

  jobs:
    rubocop:
      executor: docker/machine
      steps:
        - rubocop/rubocop:
            options:
              --parallel

workflows:
  lint:
    jobs:
      - rubocop


#    hadolint:
#      executor: docker/machine
#      steps:
#        - docker/hadolint:
#            dockerfiles: Dockerfile

#jobs:
#  rubocop:
#    executor: docker/machine
#    steps:
#      - rubocop/rubocop:
#          options:
#            --parallel

#  hadolint:
#    steps:
#      - docker/hadolint:
#          dockerfiles: Dockerfile

  #rspec:
  #  jobs:
  #    - rspec

#  shellcheck:
#    steps:
#      - shellcheck/check:
#          dir: .

#  build_test:
#    steps:
#      - docker/publish:
#          image: $CIRCLE_PROJECT_USERNAME/testing
#          use-docker-credentials-store: true

  #rspec2:
  #  jobs:
  #    - testinfra

#  docker_build:
#    steps:
#      - docker/publish:
#          image: $CIRCLE_PROJECT_USERNAME/libvirt
#          use-docker-credentials-store: true

