version: 2.1
orbs:
  rubocop: hanachin/rubocop@0.0.6
  docker: circleci/docker@
workflows:
  rubocop:
    jobs:
      - rubocop/rubocop
  hadolint:
    jobs:
      - docker/hadolint
    dockerfile: .
