---
name: Pull

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Build and scan image
        uses: ISID/build-and-scan-image@main
        with:
          tag: "libvirt"
          path: "."
